/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StravaCallbackRouteImport } from './routes/strava-callback'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthCallbackRouteImport } from './routes/auth-callback'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedPlanRouteImport } from './routes/_authed/plan'
import { Route as AuthedChatsRouteImport } from './routes/_authed/chats'
import { Route as AuthedPlanIndexRouteImport } from './routes/_authed/plan.index'
import { Route as AuthedChatsIndexRouteImport } from './routes/_authed/chats.index'
import { Route as AuthedPlanPlanIdRouteImport } from './routes/_authed/plan.$planId'
import { Route as AuthedChatsChatIdRouteImport } from './routes/_authed/chats.$chatId'

const StravaCallbackRoute = StravaCallbackRouteImport.update({
  id: '/strava-callback',
  path: '/strava-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth-callback',
  path: '/auth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPlanRoute = AuthedPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedChatsRoute = AuthedChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPlanIndexRoute = AuthedPlanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedPlanRoute,
} as any)
const AuthedChatsIndexRoute = AuthedChatsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedChatsRoute,
} as any)
const AuthedPlanPlanIdRoute = AuthedPlanPlanIdRouteImport.update({
  id: '/$planId',
  path: '/$planId',
  getParentRoute: () => AuthedPlanRoute,
} as any)
const AuthedChatsChatIdRoute = AuthedChatsChatIdRouteImport.update({
  id: '/$chatId',
  path: '/$chatId',
  getParentRoute: () => AuthedChatsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/strava-callback': typeof StravaCallbackRoute
  '/chats': typeof AuthedChatsRouteWithChildren
  '/plan': typeof AuthedPlanRouteWithChildren
  '/chats/$chatId': typeof AuthedChatsChatIdRoute
  '/plan/$planId': typeof AuthedPlanPlanIdRoute
  '/chats/': typeof AuthedChatsIndexRoute
  '/plan/': typeof AuthedPlanIndexRoute
}
export interface FileRoutesByTo {
  '/auth-callback': typeof AuthCallbackRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/strava-callback': typeof StravaCallbackRoute
  '/': typeof AuthedIndexRoute
  '/chats/$chatId': typeof AuthedChatsChatIdRoute
  '/plan/$planId': typeof AuthedPlanPlanIdRoute
  '/chats': typeof AuthedChatsIndexRoute
  '/plan': typeof AuthedPlanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/auth-callback': typeof AuthCallbackRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/strava-callback': typeof StravaCallbackRoute
  '/_authed/chats': typeof AuthedChatsRouteWithChildren
  '/_authed/plan': typeof AuthedPlanRouteWithChildren
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/chats/$chatId': typeof AuthedChatsChatIdRoute
  '/_authed/plan/$planId': typeof AuthedPlanPlanIdRoute
  '/_authed/chats/': typeof AuthedChatsIndexRoute
  '/_authed/plan/': typeof AuthedPlanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth-callback'
    | '/login'
    | '/logout'
    | '/signup'
    | '/strava-callback'
    | '/chats'
    | '/plan'
    | '/chats/$chatId'
    | '/plan/$planId'
    | '/chats/'
    | '/plan/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth-callback'
    | '/login'
    | '/logout'
    | '/signup'
    | '/strava-callback'
    | '/'
    | '/chats/$chatId'
    | '/plan/$planId'
    | '/chats'
    | '/plan'
  id:
    | '__root__'
    | '/_authed'
    | '/auth-callback'
    | '/login'
    | '/logout'
    | '/signup'
    | '/strava-callback'
    | '/_authed/chats'
    | '/_authed/plan'
    | '/_authed/'
    | '/_authed/chats/$chatId'
    | '/_authed/plan/$planId'
    | '/_authed/chats/'
    | '/_authed/plan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  SignupRoute: typeof SignupRoute
  StravaCallbackRoute: typeof StravaCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/strava-callback': {
      id: '/strava-callback'
      path: '/strava-callback'
      fullPath: '/strava-callback'
      preLoaderRoute: typeof StravaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-callback': {
      id: '/auth-callback'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/plan': {
      id: '/_authed/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AuthedPlanRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/chats': {
      id: '/_authed/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthedChatsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/plan/': {
      id: '/_authed/plan/'
      path: '/'
      fullPath: '/plan/'
      preLoaderRoute: typeof AuthedPlanIndexRouteImport
      parentRoute: typeof AuthedPlanRoute
    }
    '/_authed/chats/': {
      id: '/_authed/chats/'
      path: '/'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthedChatsIndexRouteImport
      parentRoute: typeof AuthedChatsRoute
    }
    '/_authed/plan/$planId': {
      id: '/_authed/plan/$planId'
      path: '/$planId'
      fullPath: '/plan/$planId'
      preLoaderRoute: typeof AuthedPlanPlanIdRouteImport
      parentRoute: typeof AuthedPlanRoute
    }
    '/_authed/chats/$chatId': {
      id: '/_authed/chats/$chatId'
      path: '/$chatId'
      fullPath: '/chats/$chatId'
      preLoaderRoute: typeof AuthedChatsChatIdRouteImport
      parentRoute: typeof AuthedChatsRoute
    }
  }
}

interface AuthedChatsRouteChildren {
  AuthedChatsChatIdRoute: typeof AuthedChatsChatIdRoute
  AuthedChatsIndexRoute: typeof AuthedChatsIndexRoute
}

const AuthedChatsRouteChildren: AuthedChatsRouteChildren = {
  AuthedChatsChatIdRoute: AuthedChatsChatIdRoute,
  AuthedChatsIndexRoute: AuthedChatsIndexRoute,
}

const AuthedChatsRouteWithChildren = AuthedChatsRoute._addFileChildren(
  AuthedChatsRouteChildren,
)

interface AuthedPlanRouteChildren {
  AuthedPlanPlanIdRoute: typeof AuthedPlanPlanIdRoute
  AuthedPlanIndexRoute: typeof AuthedPlanIndexRoute
}

const AuthedPlanRouteChildren: AuthedPlanRouteChildren = {
  AuthedPlanPlanIdRoute: AuthedPlanPlanIdRoute,
  AuthedPlanIndexRoute: AuthedPlanIndexRoute,
}

const AuthedPlanRouteWithChildren = AuthedPlanRoute._addFileChildren(
  AuthedPlanRouteChildren,
)

interface AuthedRouteChildren {
  AuthedChatsRoute: typeof AuthedChatsRouteWithChildren
  AuthedPlanRoute: typeof AuthedPlanRouteWithChildren
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedChatsRoute: AuthedChatsRouteWithChildren,
  AuthedPlanRoute: AuthedPlanRouteWithChildren,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  SignupRoute: SignupRoute,
  StravaCallbackRoute: StravaCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
